config/routes.rb
Rails.application.routes.draw do
  # Admin
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Static Pages
  root 'statics#index'
  get '/about' => 'statics#about'
  get '/contact' => 'statics#contact'
  get '/articles' => 'statics#article'

  # Productors
  get '/producteurs' => 'productors#index', as: :productors
  get '/producteurs/apiculteurs' => 'productors#apiculteurs', as: :apiculteurs
  get '/producteurs/eleveurs' => 'productors#eleveurs', as: :eleveurs
  get '/producteurs/horticulteurs' => 'productors#horticulteurs', as: :horticulteurs
  get '/producteurs/maraichers' => 'productors#maraichers', as: :maraichers
  get '/producteurs/viticulteurs' => 'productors#viticulteurs', as: :viticulteurs
  get '/producteurs/:id' => 'productors#show', as: :productor

  # Services
  get '/services' => 'services#index', as: :services
  get '/services/restaurants' => 'services#restaurants', as: :restaurants
  get '/services/marches' => 'services#marches', as: :marches
  get '/services/:id' => 'services#show', as: :service
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/productor.rb
class Productor < ApplicationRecord
  def typeprod_enum
    [
      %w(Apiculteur api), %w(Éleveur ele), %w(Horticulteur hor), %w(Maraîcher mar), %w(Viticulteur vit)
    ]
  end
end

app/models/service.rb
class Service < ApplicationRecord
  def typeprod_enum
    [
      %w(Restaurant res), %w(Marché mar)
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/productors_controller.rb
class ProductorsController < ApplicationController
  def index
    @apiculteurs = Productor.where(typeprod: "api").order(created_at: :desc).limit(3)
    @eleveurs = Productor.where(typeprod: "ele").order(created_at: :desc).limit(3)
    @horticulteurs = Productor.where(typeprod: "hor").order(created_at: :desc).limit(3)
    @maraichers = Productor.where(typeprod: "mar").order(created_at: :desc).limit(3)
    @viticulteurs = Productor.where(typeprod: "vit").order(created_at: :desc).limit(3)
  end

  def apiculteurs
    @apiculteurs = Productor.where(typeprod: "api").limit(6)
  end

  def eleveurs
    @eleveurs = Productor.where(typeprod: "ele").limit(6)
  end

  def horticulteurs
    @horticulteurs = Productor.where(typeprod: "hor").limit(6)
  end

  def maraichers
    @maraichers = Productor.where(typeprod: "mar").limit(6)
  end

  def viticulteurs
    @viticulteurs = Productor.where(typeprod: "vit").limit(6)
  end

  def show
    @productor = Productor.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @restaurants = Service.where(typeserv: "res").order(created_at: :desc).limit(3)
    @marches = Service.where(typeserv: "mar").order(created_at: :desc).limit(3)
  end

  def restaurants
    @restaurants = Service.where(typeserv: "res").order(created_at: :desc).limit(8)
  end

  def marches
    @marches = Service.where(typeserv: "mar").order(created_at: :desc).limit(8)
  end

  def show
    @service = Service.find(params[:id])
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
    @biglogo = true;
  end

  def about
  end

  def contact
  end

  def article
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productors_helper.rb
module ProductorsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :pagetitle %> - LPPB</title>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="description" content="<%= yield :meta_description  %>">
    <meta name="keywords" content="petit, panier, bordelais, bordeaux, sain, local, fruits, legumes, manger, marche, restaurant, producteur, produit, frais, ecolo, agriculteur, itineraire, balade, decouverte, bio">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@LePetitPanierB">
    <meta name="twitter:title" content="Le Petit Panier Bordelais">
    <meta name="twitter:description" content="<%= yield :twitter_description %>">
    <meta name="twitter:image" content="http://lepetitpanierbordelais.fr/images/logo.png">
    <meta name="twitter:image:alt" content="Le Petit Panier Bordelais, les producteurs locaux bordelais.">
    <meta property="og:title" content="Le Petit Panier Bordelais">
    <meta property="og:type" content="producteur">
    <meta property="og:url" content="https://lepetitpanierbordelais.fr/">
    <meta property="og:image" content="http://lepetitpanierbordelais.fr/images/logo.png">
    <meta property="og:description" content="<%= yield :og_description %>">
    <meta property="og:email" content="contact@lepetitpanierbordelais.fr">
    <link rel="canonical" href="http://lepetitpanierbordelais.fr<%= request.original_fullpath %>" />
    <link rel="publisher" href="https://plus.google.com/u/1/108017467012918746077" />


    <!-- <link rel="shortcut icon" href="images/logo.png"> -->
  </head>

  <body>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <div class="header-burger display-none">
      <p>Menu</p>
    </div>
    <div class="header-burger-content display-none">
      <%= link_to "Accueil", root_path, class:'menu-item', id:"accueil-item" %>
      <%= link_to "Services", services_path, class:'menu-item', id:"services-item" %>
      <%= link_to "Producteurs", productors_path, class:'menu-item', id:"producteurs-item" %>
      <%= link_to "À propos", about_path, class:'menu-item', id:"about-item" %>
      <%= link_to "Contact", contact_path, class:'menu-item', id:"contact-item" %>
    </div>

    <% if @biglogo %>
      <%= link_to image_tag('logo.png'), root_path, alt:"logo", id:"logo" %>
      <p id="baseline">La qualité saine et locale, pour le plaisir des plus raffinés.</p>
    <% else %>
      <%= link_to image_tag('logo.png'), root_path, alt:"logo", id:"logo2" %>
    <%end%>

    <div class="body-content">
      <div id="header">
        <%= link_to "Accueil", root_path, class:'menu-item', id:"accueil-item" %> <span>|</span> <!-- menu-item's class is to be able to make an active's class switch on click, cf.js -->
        <%= link_to "Services", services_path, class:'menu-item', id:"services-item" %> <span>|</span>
        <%= link_to "Producteurs", productors_path, class:'menu-item', id:"producteurs-item" %> <span>|</span>
        <%= link_to "À propos", about_path, class:'menu-item', id:"about-item" %><span>|</span>
        <%= link_to "Contact", contact_path, class:'menu-item', id:"contact-item" %>
      </div>

      <h1><%= yield :pagename %></h1>

      <%= yield %>

    </div>
    <footer>

    </footer>
    <script>menuLoaded();</script>
    <script>initCarousel();</script>
    <script>burger();</script>

  </body>
</html>

app/views/productors/apiculteurs.html.erb
<% content_for :pagetitle do %>Apiculteurs<% end %>
<% content_for :pagename do %>Nos apiculteurs<% end %>
<% content_for :meta_description do %>Venez parcourir les différents apiculteurs bordelais référencés par le Petit Panier Bordelais pour découvrir la source du miel de la région.<% end %>
<% content_for :twitter_description do %>Venez parcourir les différents apiculteurs bordelais référencés par le Petit Panier Bordelais pour découvrir la source du miel de la région.<% end %>
<% content_for :og_description do %>Venez parcourir les différents apiculteurs bordelais référencés par le Petit Panier Bordelais pour découvrir la source du miel de la région.<% end %>

<div class="productor-items" id="produc-api">
  <% @apiculteurs.each do |a| %>
    <div class="item-container">
      <% if a.image %>
      <%= link_to image_tag(a.image), productor_path(a) %>
      <% else %>
      <%= link_to image_tag('apiculteurs.jpg'), productor_path(a) %>
      <% end %>
      <p><%= a.name %></p>
    </div>
  <% end %>
</div>

app/views/productors/eleveurs.html.erb
<% content_for :pagetitle do %>Éleveurs<% end %>
<% content_for :pagename do %>Nos éleveurs<% end %>
<% content_for :meta_description do %>Venez parcourir les différents éleveurs bordelais référencés par le Petit Panier Bordelais pour découvrir les viandes et la charcuterie de la région.<% end %>
<% content_for :twitter_description do %>Venez parcourir les différents éleveurs bordelais référencés par le Petit Panier Bordelais pour découvrir les viandes et la charcuterie de la région.<% end %>
<% content_for :og_description do %>Venez parcourir les différents éleveurs bordelais référencés par le Petit Panier Bordelais pour découvrir les viandes et la charcuterie de la région.<% end %>

<div class="productor-items" id="produc-ele">
  <% @eleveurs.each do |e| %>
    <div class="item-container">
      <% if e.image %>
      <%= link_to image_tag(e.image), productor_path(e) %>
      <% else %>
      <%= link_to image_tag('eleveurs.jpg'), productor_path(e) %>
      <% end %>
      <p><%= e.name %></p>
    </div>
  <% end %>
</div>

app/views/productors/horticulteurs.html.erb
<% content_for :pagetitle do %>Horticulteurs<% end %>
<% content_for :pagename do %>Nos horticulteurs<% end %>
<% content_for :meta_description do %>Venez parcourir les différents horticulteurs bordelais référencés par le Petit Panier Bordelais pour découvrir les fleurs de la région.<% end %>
<% content_for :twitter_description do %>Venez parcourir les différents horticulteurs bordelais référencés par le Petit Panier Bordelais pour découvrir les fleurs de la région.<% end %>
<% content_for :og_description do %>Venez parcourir les différents horticulteurs bordelais référencés par le Petit Panier Bordelais pour découvrir les fleurs de la région.<% end %>

<div class="productor-items" id="produc-hor">
  <% @horticulteurs.each do |h| %>
    <div class="item-container">
      <% if h.image %>
      <%= link_to image_tag(h.image), productor_path(h) %>
      <% else %>
      <%= link_to image_tag('horticulteurs.jpg'), productor_path(h) %>
      <% end %>
      <p><%= h.name %></p>
    </div>
  <% end %>
</div>

app/views/productors/index.html.erb
<% content_for :pagetitle do %>Producteurs<% end %>
<% content_for :pagename do %>Nos producteurs<% end %>
<% content_for :meta_description do %>Venez parcourir les différents producteurs bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>
<% content_for :twitter_description do %>Venez parcourir les différents producteurs bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>
<% content_for :og_description do %>Venez parcourir les différents producteurs bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>

<div id="producteurs-index">
  <h3>Nos derniers apiculteurs</h3>

  <%= link_to apiculteurs_path do %>
  <%= image_tag('apiculteurs.jpg', class: "prod-index-img") %>
  <% end %>

  <h3>Nos derniers éleveurs</h3>

  <%= link_to eleveurs_path do %>
  <%= image_tag('eleveurs.jpg', class: "prod-index-img") %>
  <% end %>

  <h3>Nos derniers horticulteurs</h3>

  <%= link_to horticulteurs_path do %>
  <%= image_tag('horticulteurs.jpg', class: "prod-index-img") %>
  <% end %>

  <h3>Nos derniers maraîchers</h3>

  <%= link_to maraichers_path do %>
  <%= image_tag('maraichers.jpg', class: "prod-index-img") %>
  <% end %>

  <h3>Nos derniers viticulteurs</h3>

  <%= link_to viticulteurs_path do %>
  <%= image_tag('viticulteurs.jpg', class: "prod-index-img") %>
  <% end %>
</div>

app/views/productors/maraichers.html.erb
<% content_for :pagetitle do %>Maraîchers<% end %>
<% content_for :pagename do %>Nos maraîchers<% end %>
<% content_for :meta_description do %>Venez parcourir les différents maraîchers bordelais référencés par le Petit Panier Bordelais pour découvrir les fruits et légumes de la région.<% end %>
<% content_for :twitter_description do %>Venez parcourir les différents maraîchers bordelais référencés par le Petit Panier Bordelais pour découvrir les fruits et légumes de la région.<% end %>
<% content_for :og_description do %>Venez parcourir les différents maraîchers bordelais référencés par le Petit Panier Bordelais pour découvrir les fruits et légumes de la région.<% end %>

<div class="productor-items" id="produc-mar">
  <% @maraichers.each do |m| %>
    <div class="item-container">
      <% if m.image %>
      <%= link_to image_tag(m.image), productor_path(m) %>
      <% else %>
      <%= link_to image_tag('maraichers.jpg'), productor_path(m) %>
      <% end %>
      <p><%= m.name %></p>
    </div>
  <% end %>
</div>

app/views/productors/show.html.erb
<% content_for :pagetitle do %><%= @productor.name %><% end %>
<% content_for :pagename do %><%= @productor.name %><% end %>
<% content_for :meta_description do %>Découvrez la page de l'un des producteurs référencés sur le Petit Panier Bordelais, afin de vous faire découvrir les produits de la région.<% end %>
<% content_for :twitter_description do %>Découvrez la page de l'un des producteurs référencés sur le Petit Panier Bordelais, afin de vous faire découvrir les produits de la région.<% end %>
<% content_for :og_description do %>Découvrez la page de l'un des producteurs référencés sur le Petit Panier Bordelais, afin de vous faire découvrir les produits de la région.<% end %>

<div id="prod-show">

  <% if @productor.image %>
    <h2>Image</h2>
    <% image_tag @productor.image %>
  <%end%>

  <% if @productor.content %>
    <h2>Description</h2>
    <p><%= @productor.content %></p>
  <%end%>

  <h2>Produits</h2>
  <p><%= @productor.products %></p>

  <% if @productor.wineapp %>
  <h2>Apppelation de vin</h2>
  <p><%= @productor.wineapp %></p>
  <% end %>

  <h2>Localisation</h2>

  <% if @productor.onsite %>
  <h3>Sur site</h3>
  <p><%= @productor.onsite %></p>
  <% end %>

  <% if @productor.market %>
  <h3>Marchés</h3>
  <p><%= @productor.market %></p>
  <% end %>

  <% if @productor.amap %>
  <h3>AMAP</h3>
  <p><%= @productor.amap %></p>
  <% end %>

  <% if @productor.other %>
  <h3>Autres</h3>
  <p><%= @productor.other %></p>
  <% end %>

  <br>
  <%= link_to "Retour", "#", onclick: "history.back()" %>

</div>

app/views/productors/viticulteurs.html.erb
<% content_for :pagetitle do %>Viticulteurs<% end %>
<% content_for :pagename do %>Nos viticulteurs<% end %>
<% content_for :meta_description do %>Venez parcourir les différents viticulteurs bordelais référencés par le Petit Panier Bordelais pour découvrir les vins de la région.<% end %>
<% content_for :twitter_description do %>Venez parcourir les différents viticulteurs bordelais référencés par le Petit Panier Bordelais pour découvrir les vins de la région.<% end %>
<% content_for :og_description do %>Venez parcourir les différents viticulteurs bordelais référencés par le Petit Panier Bordelais pour découvrir les vins de la région.<% end %>

<div class="productor-items" id="produc-hor">
  <% @viticulteurs.each do |v| %>
    <div class="item-container">
      <% if v.image %>
      <%= link_to image_tag(v.image), productor_path(v) %>
      <% else %>
      <%= link_to image_tag('viticulteurs.jpg'), productor_path(v) %>
      <% end %>
      <p><%= v.name %></p>
    </div>
  <% end %>
</div>

app/views/services/index.html.erb
<% content_for :pagetitle do %>Services<% end %>
<% content_for :pagename do %>Nos services<% end %>
<% content_for :meta_description do %>Venez parcourir les différents services bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>
<% content_for :twitter_description do %>Venez parcourir les différents services bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>
<% content_for :og_description do %>Venez parcourir les différents services bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>

<div id="services-index">

<!-- RESTAURANTS -->

  <h3>Nos derniers restaurants</h3>

  <%= link_to restaurants_path do %>
  <%= image_tag('bread.jpg', class: "serv-index-img") %>
  <% end %>

<!-- MARCHE -->

  <h3>Nos derniers marchés</h3>

  <%= link_to marches_path do %>
  <%= image_tag('paysans.jpg', class: "serv-index-img") %>
  <% end %>

</div>

app/views/services/marches.html.erb
<% content_for :pagetitle do %>Marchés<% end %>
<% content_for :pagename do %>Nos marchés<% end %>
<% content_for :meta_description do %>Venez parcourir les différents marchés bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>
<% content_for :twitter_description do %>Venez parcourir les différents marchés bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>
<% content_for :og_description do %>Venez parcourir les différents marchés bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>

<div class="services-items" id="service-marche">
  <% @marches.each do |m| %>
    <div class="item-container">
      <% if m.image %>
      <%= link_to image_tag(m.image), service_path(m) %>
      <% else %>
      <%= link_to image_tag('paysans.jpg'), service_path(m) %>
      <% end %>
      <p><%= m.name %></p>
    </div>
  <% end %>
</div>

<p><%= link_to "Voir plus", root_path, class:"red-button" %></p>

app/views/services/restaurants.html.erb
<% content_for :pagetitle do %>Restaurants<% end %>
<% content_for :pagename do %>Nos restaurants<% end %>
<% content_for :meta_description do %>Venez parcourir les différents restaurants bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>
<% content_for :twitter_description do %>Venez parcourir les différents restaurants bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>
<% content_for :og_description do %>Venez parcourir les différents restaurants bordelais référencés par le Petit Panier Bordelais pour découvrir les produits de la région.<% end %>

<div class="services-items" id="service-restau">
  <% @restaurants.each do |r| %>
    <div class="item-container">
      <% if r.image %>
      <%= link_to image_tag(r.image), service_path(r) %>
      <% else %>
      <%= link_to image_tag('bread.jpg'), service_path(r) %>
      <% end %>
      <p><%= r.name %></p>
    </div>
  <% end %>
</div>

<p><%= link_to "Voir plus", root_path, class:"red-button" %></p>

app/views/services/show.html.erb
<% content_for :pagetitle do %><%= @service.name %><% end %>
<% content_for :pagename do %><%= @service.name %><% end %>
<% content_for :meta_description do %>Découvrez la page de l'un de nos services référencés sur le Petit Panier Bordelais, afin de vous faire découvrir les produits de la région.<% end %>
<% content_for :twitter_description do %>Découvrez la page de l'un de nos services référencés sur le Petit Panier Bordelais, afin de vous faire découvrir les produits de la région.<% end %>
<% content_for :og_description do %>Découvrez la page de l'un de nos services référencés sur le Petit Panier Bordelais, afin de vous faire découvrir les produits de la région.<% end %>
<div id="serv-show">

  <h2>Adresse</h2>
  <p><%= @service.address %></p>

  <% if @service.image %>
    <h2>Image</h2>
    <% image_tag @service.image %>
  <%end%>

  <% if @service.content %>
    <h2>Description</h2>
    <p><%= @service.content %></p>
  <%end%>

  <br>

  <%= link_to "Retour", "#", onclick: "history.back()" %>

</div>

app/views/statics/about.html.erb
<% content_for :pagetitle do %>À propos<% end %>
<% content_for :pagename do %>À propos de nous<% end %>
<% content_for :meta_description do %>Découvrez plus d'informations sur le Petit Panier Bordelais, qui vous fait découvrir les producteurs locaux bordelais.<% end %>
<% content_for :twitter_description do %>Découvrez plus d'informations sur le Petit Panier Bordelais, qui vous fait découvrir les producteurs locaux bordelais.<% end %>
<% content_for :og_description do %>Découvrez plus d'informations sur le Petit Panier Bordelais, qui vous fait découvrir les producteurs locaux bordelais.<% end %>

<div id="about-page">
  <p>Parce qu’il est important de manger local et sain, Le Petit Panier Bordelais s’est fixé pour objectif
  de vous aider à trouver facilement des produits locaux dont vous serez fous ! Rejoignez la communauté
  du Petit Panier Bordelais et découvrez tout au long de la semaine des alertes et publications sur les
  marchés imminents, les producteurs locaux et restaurants partenaires. Les fruits et légumes de saison
  seront mis à l’honneur au début de chaque mois sur notre page Instagram, ce qui inspirera vos papilles
  dans la quête d’une alimentation saine et bio. </p>
  <p>Une envie de produits locaux sans passer par votre supermarché ? Venez découvrir de façon ludique
    les producteurs locaux près de chez vous ainsi que tous les produits qu’ils vous proposent !</p>

  <h2>Notre équipe</h2>

  <div class="team-container">
    <div class="team-member">
      <%= image_tag "team/roxane.jpg" %>
      <p class="member-name">Roxane Dulhoste</p>
      <p class="member-role">Rédactrice</p>
    </div>
    <div class="team-member">
      <%= image_tag "team/lea.jpg" %>
      <p class="member-name">Léa Florent</p>
      <p class="member-role">Graphiste</p>
    </div>
    <div class="team-member">
      <p class="member-name">Mathias Fratani</p>
      <p class="member-role">Community Manager</p>
    </div>
    <div class="team-member">
      <%= image_tag "team/lolita.jpg" %>
      <p class="member-name">Lolita Gaudé</p>
      <p class="member-role">Graphiste</p>
    </div>
    <div class="team-member">
      <%= image_tag "team/seb.jpg" %>
      <p class="member-name">Sébastien Gaya</p>
      <p class="member-role">Développeur back-end</p>
    </div>
    <div class="team-member">
      <%= image_tag "team/mathieu.jpg" %>
      <p class="member-name">Mathieu Harribey</p>
      <p class="member-role">Développeur front-end</p>
    </div>
  </div>

</div>

app/views/statics/contact.html.erb
<% content_for :pagetitle do %>Contact<% end %>
<% content_for :pagename do %>Contactez-nous<% end %>
<% content_for :meta_description do %>Contactez le Petit Panier Bordelais si vous souhaitez être référencé dans nos différentes catégories ou pour tout renseignement complémentaire.<% end %>
<% content_for :twitter_description do %>Contactez le Petit Panier Bordelais si vous souhaitez être référencé dans nos différentes catégories ou pour tout renseignement complémentaire.<% end %>
<% content_for :og_description do %>Contactez le Petit Panier Bordelais si vous souhaitez être référencé dans nos différentes catégories ou pour tout renseignement complémentaire.<% end %>

<div id="contact">
  <hr><hr><br>
  <p> 1 rue Jacques Ellul, 33000 Bordeaux </p>
  <p> contact@lepetitpanierbordelais.fr </p>
  <p> 06 70 98 67 88 </p>
</div>

app/views/statics/index.html.erb
<% content_for :pagetitle do %>Accueil<% end %>
<% content_for :pagename do %>Le Petit Panier Bordelais<% end %>
<% content_for :meta_description do %>Le Petit Panier Bordelais vous fait découvrir les producteurs locaux bordelais, ainsi que les restaurants et marchés proposant leurs produits sains et frais.<% end %>
<% content_for :twitter_description do %>Le Petit Panier Bordelais vous fait découvrir les producteurs locaux bordelais, ainsi que les restaurants et marchés proposant leurs produits sains et frais.<% end %>
<% content_for :og_description do %>Le Petit Panier Bordelais vous fait découvrir les producteurs locaux bordelais, ainsi que les restaurants et marchés proposant leurs produits sains et frais.<% end %>

<div id="homepage">
  <div id="about">
    <div id="text">
      <h3> Qui sommes nous ?</h3>
      <p>Notre plateforme se veut être un site de référence permettant aux utilisateurs d’accéder aux produits locaux près de chez eux, de rencontrer les producteurs, de découvrir des marchés, des services près de chez eux tels que les AMAP, et enfin de découvrir des produits de qualité à prix abordable, et de se divertir grâce à des itinéraires « Découvertes » proposant un tour de la ville autour de dégustations et de découverte de produits locaux.
         L’itinéraire reste un plus, l’axe principal est le référencement des producteurs et des produits.
      </p>
      <p>Finalement, Le Petit Panier Bordelais est une source d’information, de découverte, de surprise, et en bonus de divertissement. Ce service ne proposera pas d’échanges entre les utilisateurs, ce qui n’implique pas de modération, toutefois les utilisateurs ou producteurs pourront proposer des magasins, restaurants, producteurs, produits à ajouter à notre plateforme pour l’enrichir.</p>

      <%= link_to 'Découvrir nos articles', articles_path ,class:"red-button" %>
    </div>
  </div>

  <div id="vendeurs">
    <div class="left-part">
      <h3>Nos Vendeurs</h3>
      <p> Vous voulez changer un peu des marchés et voulez trouver des vendeurs de produits locaux près de chez vous ? Retrouvez ici tous nos vendeurs présents dans l'agglomération bordelaise qui seront ravis de satisfaire vos besoins, n'hésitez pas à les contacter !
      </p>
      <%= link_to 'Découvrir', services_path,class:"red-button" %>
    </div>
    <div class="right-part"></div>
  </div>

  <div id="producteurs">
    <div class="left-part"></div>
    <div class="right-part">
      <h3>Nos Producteurs</h3>
      <p> Acheter vos aliments directement chez nos producteurs, vous découvrirez des produits exeptionnels pour un coût réduit et une qualité sans pareille. Contactez nos producteurs grâce à liste disponible sur notre plateforme, les répartissant par activités et localisation. Ils sont présents aux alentours de Bordeaux, et sûrement près de chez vous !
      </p>
      <%= link_to 'Découvrir', productors_path, class:"red-button" %>
    </div>
  </div>
</div>